name: ci
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
    - uses: docker/login-action@v1
      with:
          username: "15061995"
          password: "Sasi@150695"
    - name: Build the Docker Image 

      run: docker build . --file Dockerfile --tag 15061995/sms_api
    - name: Push the Docker Image 
      run: docker push 15061995/sms_api
          
