
name: Node CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:

      matrix:

        node-version: [14.x]

    steps:

    - uses: actions/checkout@v1

    - name: Use Node.js ${{ matrix.node-version }}

      uses: actions/setup-node@v1

      with:

        node-version: ${{ matrix.node-version }} 

    - name: Test the Testcases 

      run: |

        npm install

        npm run build --if-present

        npm test

    - name: Login to Docker Hub

      run: docker login --username "15061995" --password "Sasi@150695"

    - name: Build the Docker Image 

      run: docker build . --file Dockerfile --tag 15061995/test2:v2

    - name: Push the Docker Image 

      run: docker push 15061995/test2:v2
      
    - name: docker login
    
      run: docker login --username "15061995" --password "Sasi@150695"
      
    - name: pull the image from docker
    
      run: docker pull 15061995/test2:v2
      
    - name: docker run
    
      run: docker run -d -p 3500:80 --name "testserver" 15061995/test1:latest

      
